config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :survivors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :survivors
      resources :transfers
      resources :items
    end
  end

end

app/models/survivor.rb
class Survivor < ApplicationRecord
   has_many :bags
   accepts_nested_attributes_for :bags, reject_if: :all_blank, allow_destroy: true
end

app/controllers/api/v1/survivors_controller.rb
class API::V1::SurvivorsController < ApplicationController

  def index
    @survivors = Survivor.all
        render :json => @survivors.map { |survivor| {:id => survivor.id, :name => survivor.name, :infected => survivor.infected} }
  end

def create
    @survivor = Survivor.new(survivor_params)
    if @survivor.save
      respond_with @survivor
    end
  end


    def show
  @survivor = Survivor.where(id: params[:id])
  @items = Bag.where(survivor_id: params[:id])
respond_to do |format|
  format.json  { render :json => {:survivor => @survivor.map { |survivor| {:id => survivor.id, :name => survivor.name, :infected => survivor.infected, :gender => survivor.gender, :latitude => survivor.latitude, :longitude => survivor.longitude, :age => survivor.age} },
                                  :inventory => @items.map { |items| {:id => items.id, :quantity => items.quantity, :item => items.item_ref}} }}
end
end
private
 def set_survivor
      @survivor = Survivor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survivor_params
      params.require(:survivor).permit(:name, :gender, :longitude, :latitude, :age, :infected, bags_attributes: [:id, :item_ref, :quantity])
    end
end

app/controllers/survivors_controller.rb
class SurvivorsController < ApplicationController
  before_action :set_survivor, only: [:show, :edit, :update, :destroy]

  # GET /survivors
  # GET /survivors.json
  def index
    @survivors = Survivor.all
  end

  # GET /survivors/1
  # GET /survivors/1.json
  def show
  end

  # GET /survivors/new
  def new
    @survivor = Survivor.new
  end

  # GET /survivors/1/edit
  def edit
  end

  # POST /survivors
  # POST /survivors.json
  def create

    @survivor = Survivor.new(survivor_params)
    respond_to do |format|
      if @survivor.save
        format.html { redirect_to @survivor, notice: 'Survivor was successfully created.' }
        format.json { render :show, status: :created, location: @survivor }
      else
        format.html { render :new }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survivors/1
  # PATCH/PUT /survivors/1.json
  def update
    respond_to do |format|
      if @survivor.update(survivor_params)
        format.html { redirect_to @survivor, notice: 'Survivor was successfully updated.' }
        format.json { render :show, status: :ok, location: @survivor }
      else
        format.html { render :edit }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survivors/1
  # DELETE /survivors/1.json
  def destroy
    @survivor.destroy
    respond_to do |format|
      format.html { redirect_to survivors_url, notice: 'Survivor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survivor
      @survivor = Survivor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survivor_params
      params.require(:survivor).permit(:name, :gender, :longitude, :latitude, :age, :infected, bags_attributes: [:id, :item_ref, :quantity])
    end
end

app/helpers/survivors_helper.rb
module SurvivorsHelper
end

app/views/survivors/_bag_fields.html.erb
<div class="nested-fields ls-box">

<label class="ls-label">
      <b class="ls-label-text">Valor</b><br>
    <%= f.number_field :quantity %>
           <%= f.select :item_ref, Item.all.map { |c| [c.name, c.id] } %>


    </label>


  <%= link_to_remove_association "Remover Item", f, :class=> "ls-btn-danger" %>
</div>

app/views/survivors/_form.html.erb
<%= form_for(survivor) do |f| %>
  <% if survivor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survivor.errors.count, "error") %> prohibited this survivor from being saved:</h2>

      <ul>
      <% survivor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :infected %>
    <%= f.check_box :infected %>
  </div>

      <div id="partial_outcome">
        <%= f.fields_for :bags do |bag| %>
          <%= render 'bag_fields', f: bag %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Adicionar Item ao Inventorio', f, :bags, :class => '' %>
        </div>
      </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/survivors/edit.html.erb
<h1>Editing Survivor</h1>

<%= render 'form', survivor: @survivor %>

<%= link_to 'Show', @survivor %> |
<%= link_to 'Back', survivors_path %>

app/views/survivors/index.html.erb
<h1 class="ls-title-intro ls-ico-users ">Survivors</h1>


<table id="table_id"  class="ls-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Age</th>
      <th>Infected</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @survivors.each do |survivor| %>
      <tr>
        <td><%= survivor.name %></td>
        <td><%= survivor.gender %></td>
        <td><%= survivor.longitude %></td>
        <td><%= survivor.latitude %></td>
        <td><%= survivor.age %></td>
        <td><%= survivor.infected %></td>
        <td><%= link_to 'Show', survivor %> <%= survivor.infected ? ("You cannot Edit It") : (link_to 'Edit', edit_survivor_path(survivor)) %> <%= link_to 'Destroy', survivor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survivor', new_survivor_path, class: 'ls-btn-default'   %>

 <script >
$(document).ready( function () {
    $('#table_id').DataTable();
} );
 </script>

app/views/survivors/new.html.erb
<h1>New Survivor</h1>

<%= render 'form', survivor: @survivor %>

<%= link_to 'Back', survivors_path %>

app/views/survivors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survivor.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @survivor.gender %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @survivor.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @survivor.latitude %>
</p>

<p>
  <strong>Age:</strong>
  <%= @survivor.age %>
</p>

<p>
  <strong>Infected:</strong>
  <%= @survivor.infected %>
</p>

<%= link_to 'Edit', edit_survivor_path(@survivor) %> |
<%= link_to 'Back', survivors_path %>