config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :survivors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :survivors
      resources :transfers
      resources :items
    end
  end

end

app/models/transfer.rb
class Transfer < ApplicationRecord
end

app/controllers/api/v1/transfers_controller.rb
class API::V1::TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
    render :json => @transfers.map { |transfer| {:id => transfer.id} }

  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:survivor_in, :quantity_in, :item_in, :survivor_out, :quantity_out, :item_out)
    end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)
    bagin =  Bag.where(survivor_id: @transfer.survivor_in)
    bagin.each do |bag|
        if bag.item_ref == @transfer.item_in
          if bag.quantity <= @transfer.quantity_in
            @points = Item.where(id: @transfer.item_in)
            @points_in = @transfer.quantity_in * @points.points
          else
            @notice =  'Transfer couldnt happen cause Quantity of items unavaible from the first survivor'
            return new_transfer_path
          end
        else
          @notice= 'Transfer couldnt happen cause items unavaible from the first survivor'
          return new_transfer_path
        end
    end
    bagout =  Bag.where(survivor_id: @transfer.survivor_out)
    bagout.each do |bag|
        if bag.item_ref == @transfer.item_out
          if bag.quantity <= @transfer.quantity_out
            @points = Item.where(id: @transfer.item_out)
            @points_out = @transfer.quantity_out * @points.points
          else
            @notice =  'Transfer couldnt happen cause Quatity of items unavaible from the second survivor'
             return new_transfer_path
          end
        else
          @notice =  'Transfer couldnt happen cause items unavaible from the second survivor'
             return new_transfer_path
      end
    end

    if @points_in == @points_out
      @bagin = Bag.where(survivor_id: @transfer.survivor_in).where(item_id: @transfer.item_in)
      @bagout = Bag.where(survivor_id: @transfer.survivor_out).where(item_id: @transfer.item_out)
      @bagin.survivor_id = @transfer.survivor_out
      @bagout.survivor_id = @transfer.survivor_in
      @bagin.save
      @bagout.save
      @transfer.save
        redirect_to @transfer, notice: 'Transfer was successfully created. Points changed'
    else
      @notice =  'Transfer couldnt happen'
             return new_transfer_path
    end

  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:survivor_in, :quantity_in, :item_in, :survivor_out, :quantity_out, :item_out)
    end
end

app/helpers/transfer_helper.rb
module TransferHelper
end

app/views/transfers/_form.html.erb
<%= form_for(transfer) do |f| %>
  <% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survivor_in %>
    <%= f.select :survivor_in, Survivor.where(infected: false).map { |c| [c.name, c.id] } %>

  </div>

  <div class="field">
    <%= f.label :quantity_in %>
    <%= f.number_field :quantity_in %>
  </div>

  <div class="field">
    <%= f.label :item_in %>
    <%= f.select :item_in, Item.all.map { |c| [c.name, c.id] } %>

  </div>

  <div class="field">
    <%= f.label :survivor_out %>
    <%= f.select :survivor_out, Survivor.where(infected: false).map { |c| [c.name, c.id] } %>

  </div>

  <div class="field">
    <%= f.label :quantity_out %>
    <%= f.number_field :quantity_out %>
  </div>

  <div class="field">
    <%= f.label :item_out %>
        <%= f.select :item_out, Item.all.map { |c| [c.name, c.id] } %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<h1 class="ls-title-intro ls-ico-dashboard ">Transfer Items</h1>


<table  id="table_id" class="ls-table">
  <thead>
    <tr>
      <th>Survivor in</th>
      <th>Quantity in</th>
      <th>Item in</th>
      <th>Survivor out</th>
      <th>Quantity out</th>
      <th>Item out</th>
      <th >Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= Survivor.where(id: transfer.survivor_in).pluck(:name) %></td>
        <td><%= transfer.quantity_in %></td>
        <td><%= Item.where(id: transfer.item_in).pluck(:name) %></td>
        <td><%= Survivor.where(id: transfer.survivor_out).pluck(:name)  %></td>
        <td><%= transfer.quantity_out %></td>
        <td><%= Item.where(id: transfer.item_out).pluck(:name)%></td>
        <td><%= link_to 'Show', transfer %> <%= link_to 'Edit', edit_transfer_path(transfer) %> <%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path, class: 'ls-btn-default'   %>

 <script >
$(document).ready( function () {
    $('#table_id').DataTable();
} );
 </script>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>
<p id="notice"><%= @notice %></p>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Survivor in:</strong>
  <%= @transfer.survivor_in %>
</p>

<p>
  <strong>Quantity in:</strong>
  <%= @transfer.quantity_in %>
</p>

<p>
  <strong>Item in:</strong>
  <%= @transfer.item_in %>
</p>

<p>
  <strong>Survivor out:</strong>
  <%= @transfer.survivor_out %>
</p>

<p>
  <strong>Quantity out:</strong>
  <%= @transfer.quantity_out %>
</p>

<p>
  <strong>Item out:</strong>
  <%= @transfer.item_out %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>